[workspace]
members = ["math", "crypto", "gpu", "benches"]
exclude = ["ensure-no_std"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
iai-callgrind = "0.3.1"

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3
