[package]
name = "lambdaworks-plonk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambdaworks-math = { workspace = true, features = ["std"] }
lambdaworks-crypto = { workspace = true, features = ["std"] }
serde = "1.0"
serde_json = "1.0"
