[package]
name = "lambdaworks-math"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = {version = "0.8.5", default-features = false}
thiserror = "1.0.38"

# rayon
rayon = { version = "1.7.0", optional = true }
heapless = "0.7.16"

# metal
metal = { version = "0.24.0", optional = true }
objc = { version = "0.2.7", optional = true }

# cuda
cudarc = { version = "0.9.7", optional = true }

lambdaworks-gpu = { path = "../gpu" }

[dev-dependencies]
proptest = "1.1.0"
criterion = "0.4"
const-random = "0.1.15"
iai-callgrind.workspace = true

[features]
rayon = ["dep:rayon"]
default = ["rayon", "std"]
std = []

# gpu
metal = ["dep:metal", "dep:objc", "lambdaworks-gpu/metal"]
cuda = ["dep:cudarc"]

[[bench]]
name = "criterion_elliptic_curve"
harness = false

[[bench]]
name = "criterion_polynomial"
harness = false

[[bench]]
name = "iai_polynomial"
harness = false

[[bench]]
name = "criterion_field"
harness = false

[[bench]]
name = "iai_field"
harness = false

[[bench]]
name = "criterion_msm"
harness = false
required-features = ["rayon"]

[[bench]]
name = "criterion_fft"
harness = false

[[bench]]
name = "iai_fft"
harness = false

[[bench]]
name = "criterion_metal"
harness = false
required-features = ["metal"]
