[package]
name = "lambdaworks-math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
thiserror = "1.0.38"
rayon = { version = "1.7.0", optional = true }

[dev-dependencies]
proptest = "1.1.0"
criterion = "0.4"
const-random = "0.1.15"
iai = "0.1"

[features]
rayon = ["dep:rayon"]

default = ["rayon"]

[[bench]]
name = "criterion_polynomial"
harness = false

[[bench]]
name = "iai_polynomial"
harness = false

[[bench]]
name = "criterion_field"
harness = false

[[bench]]
name = "iai_field"
harness = false

[[bench]]
name = "criterion_msm"
harness = false
required-features = ["rayon"]
