[package]
name = "lambdaworks-stark-fuzz"
version.workspace = true
edition.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
lambdaworks-math = { workspace = true }
libfuzzer-sys = { workspace = true }
stark-platinum-prover = { workspace = true }

[[bin]]
name = "deserialize_stark_proof"
path = "fuzz_targets/deserialize.rs"
test = false
doc = false
