[package]
name = "lambdaworks-stark-fuzz"
version.workspace = true
edition.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
lambdaworks-math = { workspace = true }
libfuzzer-sys = { workspace = true }

[dependencies.lambdaworks-stark]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "deserialize_stark_proof"
path = "fuzz_targets/deserialize.rs"
test = false
doc = false
