[package]
name = "cuda_fuzz"
version.workspace = true
edition.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
lambdaworks-math = { workspace = true, features = ["cuda"] }
lambdaworks-gpu = { workspace = true, features = ["cuda"] }
libfuzzer-sys = { workspace = true }
 
[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
