[package]
name = "lambdaworks-benches"
version.workspace = true
edition.workspace = true

[dependencies]
ark-ff = { git = "https://github.com/arkworks-rs/algebra", rev = "ef8f758" }
ark-test-curves = { git = "https://github.com/arkworks-rs/algebra", rev = "ef8f758" }
ark-std = "0.4.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
starknet-curve = { git = "https://github.com/xJonathanLEI/starknet-rs" }
starknet-ff = { git = "https://github.com/xJonathanLEI/starknet-rs" }
starknet-crypto = { git = "https://github.com/xJonathanLEI/starknet-rs" }
pathfinder-crypto = { git = "https://github.com/eqlabs/pathfinder.git" }

[dependencies.lambdaworks-math]
path = "../math"

[dependencies.lambdaworks-crypto]
path = "../crypto"

[dev-dependencies]
criterion = { version = "0.5.1", default-features = false }
rand_chacha = "0.3.1"

[[bench]]
name = "add"
harness = false

[[bench]]
name = "mul"
harness = false

[[bench]]
name = "sub"
harness = false

[[bench]]
name = "invert"
harness = false

[[bench]]
name = "sqrt"
harness = false

[[bench]]
name = "pow"
harness = false

[[bench]]
name = "point"
harness = false

[[bench]]
name = "poseidon"
harness = false
