[book]
authors = ["Javier Chatruc", "Estéfano Bargas", "Mauro Toscano", "Diego Kingston", "Sergio Chouhy", "Agustín Garassino", "Mariano Nicolini"]
language = "en"
multilingual = false
src = "src"
title = "docs"

[preprocessor.katex]
