[package]
name = "lambdaworks-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.lambdaworks-math]
path = "../math"

[dependencies]
sha3 = "0.10.6"

[dependencies.rand]
version = "0.8"

[features]
test_fiat_shamir = []
