[package]
name = "lambdaworks-crypto"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.lambdaworks-math]
path = "../math"

[dependencies]
sha3 = "0.10.6"
thiserror = "1.0.38"

[dependencies.rand]
version = "0.8"

[dev-dependencies]
criterion = "0.4"
iai-callgrind.workspace = true

[features]
test_fiat_shamir = []

[[bench]]
name = "criterion_merkle"
harness = false

[[bench]]
name = "iai_merkle"
harness = false
