name: Benchmarks 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust 1.66.1 
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.66.1 
          override: true
    - uses: actions/checkout@v3
    - name: Run benchmark
      run: cargo bench --bench all_benchmarks -- --output-format bencher | tee output.txt
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'cargo'
        output-file-path: output.txt
        benchmark-data-dir-path: "./bench"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Push and deploy GitHub pages branch automatically
        auto-push: ${{ github.event_name != 'pull_request' }}
        alert-threshold: '130%'
        comment-on-alert: true
        alert-comment-cc-users: '@unbalancedparentheses'
