name: CI

on:
  push:
    branches: [ main ]

jobs:
  cache_iai_benchs:
    name: Cache iai benchs of main
    runs-on: ubuntu-20.04
    steps:
    - name: Install valgrind
      run: |
        sudo apt update
        sudo apt-get install -y valgrind
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable
    - uses: actions/checkout@v3
    - name: Initialize iai cache for ${{ github.sha }}
      uses: actions/cache@v3
      id: cache-iai-results
      with:
        path: |
          target/iai/
          !target/iai/**.old
        key: ${{ runner.os }}-iai-benchmark-cache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-iai-benchmark-cache-
    - name: Run benchmarks
      if: ${{ steps.cache-iai-results.outputs.cache-hit != 'true' }}
      run: cargo bench --no-fail-fast --bench "iai_*"
